version: '3'
dotenv: ['.env']
vars:
  BASE: docker compose --env-file $DOCKER_STACK_PATH/.env.cms.local -f $DOCKER_STACK_PATH/docker-compose.yml
tasks:
  # Docker Compose Management
  docker:up:
    desc: Start docker compose services
    cmd: '{{.BASE}} up -d'
  docker:down:
    desc: Stop docker compose services
    cmd: '{{.BASE}} down'
  docker:reload:
    desc: Restart all services (apply configs)
    cmds:
      - '{{.BASE}} down'
      - '{{.BASE}} up -d'
  # Laravel Application Management
  app:upgrade:
    desc: Clear Laravel caches and run migrations
    cmds:
      - '{{.BASE}} exec php /bin/sh -c ''php artisan optimize:clear'''
      - '{{.BASE}} exec php /bin/sh -c ''php artisan config:clear'''
      - '{{.BASE}} exec php /bin/sh -c ''php artisan cache:clear'''
      - '{{.BASE}} exec php /bin/sh -c ''php artisan view:clear'''
      - '{{.BASE}} exec php /bin/sh -c ''php artisan migrate'''
  app:clear:
    desc: Clear all Laravel caches
    cmd: '{{.BASE}} exec php /bin/sh -c "php artisan optimize:clear"'
  app:artisan:
    desc: Run artisan command (usage - task app:artisan -- migrate:status)
    cmd: '{{.BASE}} exec php /bin/sh -c "php artisan {{.CLI_ARGS}}"'
  # Database Management
  db:fresh:
    desc: Reset database (fresh migration)
    cmd: '{{.BASE}} exec php /bin/sh -c "php artisan migrate:fresh"'
  db:seed:
    desc: Reset database with seeding
    cmd: '{{.BASE}} exec php /bin/sh -c "php artisan migrate:fresh --seed"'
  # Build frontend assets
  build:npm:
    desc: Build frontend assets (vite build)
    cmd: '{{.BASE}} exec php /bin/sh -c "npm run build"'
  build:dev:
    desc: Start Vite dev server
    cmd: '{{.BASE}} exec php /bin/sh -c "npm run dev"'
