version: '3'
dotenv: ['.env']
vars:
  # docker compose doesn't expand shell variables from env files
  BASE: docker compose --env-file ./.env -f {{.DOCKER_STACK_PATH}}/docker-compose.yml
tasks:
  # Docker Compose Management
  docker:up:
    desc: Start docker compose services
    cmd: '{{.BASE}} up -d'
  docker:down:
    desc: Stop docker compose services
    cmd: '{{.BASE}} down'
  docker:reload:
    desc: Restart all services (apply configs)
    cmds:
      - '{{.BASE}} down'
      - '{{.BASE}} up -d'
  docker:php:exec:
    desc: execute code inside php service container (usage - go-task docker:php:exec -- composer --version)
    cmd: '{{.DOCKER_PHP_EXEC}} {{.CLI_ARGS}}'
  # Laravel Application Management
  app:cache:
    desc: Clear Laravel caches
    cmds:
      - '{{.DOCKER_PHP_EXEC}} php artisan optimize:clear'
      - '{{.DOCKER_PHP_EXEC}} php artisan config:clear'
      - '{{.DOCKER_PHP_EXEC}} php artisan cache:clear'
      - '{{.DOCKER_PHP_EXEC}} php artisan view:clear'
  app:clear:
    desc: Clear all Laravel caches
    cmd: '{{.DOCKER_PHP_EXEC}} php artisan optimize:clear'
  app:fix-perms:
    desc: Fix Laravel storage and cache permissions
    cmd: '$DOCKER_STACK_PATH/scripts/laravel-fix-perms.sh'
  # Database Management
  db:fresh:
    desc: Reset database (fresh migration)
    cmd: '{{.DOCKER_PHP_EXEC}} php artisan migrate:fresh'
  db:seed:
    desc: Reset database with seeding
    cmd: '{{.DOCKER_PHP_EXEC}} php artisan migrate:fresh --seed'
  # Build frontend assets
  build:npm:
    desc: Build frontend assets (vite build)
    cmd: '{{.DOCKER_PHP_EXEC}} npm run build'
  build:dev:
    desc: Start Vite dev server
    cmd: '{{.DOCKER_PHP_EXEC}} npm run dev'
